Repository NewsFeedProject-7/NewsFeedProject-7, pull requests merged in 2025-08, with the labels that each got.

#28 chore: application-local.yml 로 관리하도록 변경
  .gitignore
  src/main/resources/application-example.yml
  src/main/resources/application.yml
Labels: 🧹 chore

#30 BaseEntity, DeletableEntity 최초생성
  src/main/java/org/example/newsfeedproejct/global/BaseEntity.java
  src/main/java/org/example/newsfeedproejct/global/GlobalException.java
  src/main/java/org/example/newsfeedproejct/global/SoftDeletableEntity.java
Labels: ✨ feat

#32 chore(global): 변수명 언더바 제거
  src/main/java/org/example/newsfeedproejct/global/entity/BaseEntity.java
  src/main/java/org/example/newsfeedproejct/global/entity/SoftDeletableEntity.java
Labels: ⚡️ refactor

#39 feat(exception) : 익셉션기능추가
  src/main/java/org/example/newsfeedproejct/global/dto/ErrorResponseDto.java
  src/main/java/org/example/newsfeedproejct/global/entity/SoftDeletableEntity.java
  src/main/java/org/example/newsfeedproejct/global/exception/CommonErrorCode.java
  src/main/java/org/example/newsfeedproejct/global/exception/ErrorType.java
  src/main/java/org/example/newsfeedproejct/global/exception/GlobalException.java
  src/main/java/org/example/newsfeedproejct/global/exception/GlobalExceptionHandler.java
  src/main/java/org/example/newsfeedproejct/global/exception/NotFoundException.java
  src/main/java/org/example/newsfeedproejct/global/exception/UnAuthorizedException.java
  src/main/java/org/example/newsfeedproejct/user/service/UserService.java
Labels: ✨ feat

#46 feat(comment): 댓글 생성 기능 추가
  src/main/java/org/example/newsfeedproejct/comment/controller/CommentController.java
  src/main/java/org/example/newsfeedproejct/comment/dto/CommentCreateDto.java
  src/main/java/org/example/newsfeedproejct/comment/entity/Comment.java
  src/main/java/org/example/newsfeedproejct/comment/repository/CommentRepository.java
  src/main/java/org/example/newsfeedproejct/comment/service/CommentService.java
  src/main/java/org/example/newsfeedproejct/global/exception/errorcode/CommentErrorCode.java
Labels: ✨ feat

#53 feat(board): 게시글 단건 조회 기능 추가 (댓글 리스트 포함)
  src/main/java/org/example/newsfeedproejct/board/controller/BoardController.java
  src/main/java/org/example/newsfeedproejct/board/dto/BoardSearchDetailDto.java
  src/main/java/org/example/newsfeedproejct/board/service/BoardService.java
Labels: ✨ feat

#61 feat(board): 피드 수정 기능 추가
  src/main/java/org/example/newsfeedproejct/board/controller/BoardController.java
  src/main/java/org/example/newsfeedproejct/board/dto/BoardUpdateDto.java
  src/main/java/org/example/newsfeedproejct/board/service/BoardService.java
  src/main/java/org/example/newsfeedproejct/global/exception/errorcode/BoardErrorCode.java
Labels: ✨ feat

#68 feat(user): 회원 탈퇴 기능 추가
  src/main/java/org/example/newsfeedproejct/global/exception/errorcode/UserErrorCode.java
  src/main/java/org/example/newsfeedproejct/user/controller/UserController.java
  src/main/java/org/example/newsfeedproejct/user/dto/UserDeleteDto.java
  src/main/java/org/example/newsfeedproejct/user/service/UserService.java
Labels: ✨ feat

#90 fix(user): 회원탈퇴 시 로그아웃 처리
  src/main/java/org/example/newsfeedproejct/user/controller/UserController.java
Labels: 🐞 bug

#97 refactor(board): EntityGraph->QueryDSL
  build.gradle
  gradlew
  src/main/java/org/example/newsfeedproejct/board/dto/BoardSearchDto.java
  src/main/java/org/example/newsfeedproejct/board/repository/BoardRepository.java
  src/main/java/org/example/newsfeedproejct/board/repository/BoardRepositoryCustom.java
  src/main/java/org/example/newsfeedproejct/board/repository/BoardRepositoryImpl.java
  src/main/java/org/example/newsfeedproejct/board/service/BoardService.java
  src/main/java/org/example/newsfeedproejct/global/config/QuerydslConfig.java
Labels: ⚡️ refactor

#98 fix(board): 단건 조회 EntityGraph 추가
  src/main/java/org/example/newsfeedproejct/board/repository/BoardRepository.java
Labels: 🔧 imp

#109 refactor(follow): DB에서 처리 / 타입 변경
  src/main/java/org/example/newsfeedproejct/follow/dto/FollowFriendAnniversaryDto.java
  src/main/java/org/example/newsfeedproejct/follow/repository/FollowRepositoryCustom.java
  src/main/java/org/example/newsfeedproejct/follow/repository/FollowRepositoryCustomImpl.java
  src/main/java/org/example/newsfeedproejct/follow/service/FollowService.java
Labels: ⚡️ refactor
